### ISSUE TITLE
train on multiple gpu

### ISSUE THREAD

**Issue by ysikalie** [baldassarreFe/deep-koalarization#11]
Have you tried to train it  on multiple gpu?How?

**Comment by baldassarreFe** [comment]
Hi, no we didn't try since we only had one GPU available. If you want, I suggest reading about it in the TensorFlow documentation, but be sure to read the docs about the version we used, [1.3](https://www.tensorflow.org/versions). 
Also, if you want to work on a similar project I really suggest rewriting the architecture and the training code with a newer version of TensorFlow, a lot has changed and many things are much better/easier now. Good luck!
