### ISSUE TITLE
Pre-trained model

### ISSUE THREAD

**Issue by ShakedDovrat** [baldassarreFe/deep-koalarization#6]
Is there a pre-trained model for this? I want to do transfer learning on my dataset w/o training from scratch.

**Comment by baldassarreFe** [comment]
No, unfortunately we did not store the weights. Also, it is not in our plans to do so because the Tensorflow API has evolved a lot since we wrote this code. Before running a training session and releasing the weights this repository should be updated and modernized. 

As far as I know, there are some open source projects that used our implementation as a starting point and that might have released pre-trained models.
