### ISSUE TITLE
Inception output size

### ISSUE THREAD

**Issue by Cwei1** [baldassarreFe/deep-koalarization#8]
Hi! I'm confused as to the fusion layer. I thought Inception Resnet v2 was supposed to have 1000 classes, so  the output is supposed to be of the shape (1000, ), not 1001. Can you explain this?

**Comment by baldassarreFe** [comment]
The [original implementation](https://github.com/tensorflow/models/blob/master/research/slim/nets/inception_resnet_v2.py) of Inception ResNet v2 uses an output shape of 1001. Probably to include a "background/unknown" class. In order to use the pretrained version of Inception you must stick to those 1001 outputs or replace the final layer (and train it).
